//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "item")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub mime_type: String,
    pub size_bytes: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub checksum: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub storage_uri: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::item_facet_value::Entity")]
    ItemFacetValue,
}

impl Related<super::item_facet_value::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemFacetValue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
