//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "item_facet_value")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uq__item_facet_value__multi_timestamp")]
    pub item_id: Uuid,
    #[sea_orm(unique_key = "uq__item_facet_value__multi_timestamp")]
    pub facet_id: Uuid,
    pub is_multi_value: bool,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "uq__item_facet_value__multi_text"
    )]
    pub value_text: Option<String>,
    #[sea_orm(unique_key = "uq__item_facet_value__multi_numeric")]
    pub value_numeric: Option<Decimal>,
    #[sea_orm(unique_key = "uq__item_facet_value__multi_boolean")]
    pub value_boolean: Option<bool>,
    #[sea_orm(unique_key = "uq__item_facet_value__multi_timestamp")]
    pub value_timestamp: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::facet::Entity",
        from = "Column::FacetId",
        to = "super::facet::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Facet,
    #[sea_orm(
        belongs_to = "super::item::Entity",
        from = "Column::ItemId",
        to = "super::item::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Item,
}

impl Related<super::facet::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Facet.def()
    }
}

impl Related<super::item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Item.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
